### PR TITLE
Pass the asciidocConfig to classifyContent

### PR DESCRIPTION
**Pull request by Mogztter**
Backport: https://gitlab.com/antora/antora/-/commit/290d6f3cf45ed6bfcb4a25b1ec0d4caafe4af2c2 (introduced in Antora v2.3.0)

//cc @mojavelinux @brunchboy

### CODE REVIEW

**Comment by mojavelinux** [comment]
Although this is the right change for the long term, I'm confused why this is necessary for it to work with Antora 2.3. The classifyContent function creates an instance of the config object if it isn't passed in. Is the Lunr extension making a change to the config object that's getting lost later in the pipeline?

**Comment by mojavelinux** [comment]
I can confirm that the problem @brunchboy encountered is not in anyway related to this.

It's still a good idea to make this change, but it's not required for using the generator with Antora 2.3.

**Comment by Mogztter** [comment]
@brunchboy mentioned another issue regarding AsciiDoc attributes and I had a warning when building the Beat Link Trigger documentation site about a missing attribute.
I thought it might be related to this change but apparently no.
Thanks for your analysis. I will move forward and merge it 😀

**Comment by brunchboy** [comment]
Sorry if I added any undue confusion here. I think the only time I saw such warnings was when I was trying with an ancient version of antora-site-generator-lunr, perhaps 0.3.0?

**Comment by Mogztter** [comment]
No worries, in the end you helped me find a missing change from Antora so all good :wink:

**Pull request merged**
